title: "hi, I'm Harry. 👋"
author: "Harry Kalantzis"
description: "learning technology; instructional design; pedagogy; life; apple. <br>this is a microblog."
baseurl: "/microblog"
url: "https://harry.kalantzis.uk"
email: "hkalant@gmail.com"
permalink: "/:title/"
relative_permalinks: false
paginate: 20
paginate_path: "/page/:num/"
timezone: Europe/London # A list of all available values can be found at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

highlighter: "rouge"
markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
            profile: true

plugins:
  - jekyll-sitemap
